GENI-NSF/geni-tools

CHANGES, src/gcf-am.py
This closes track issue #804, so that AM version is logged when Aggregate manager successfully starts.
David
=> Tkt804 log am version

CHANGES, src/gcf/geni/am/am3.py
Basically, all am3 calls have code that looks like this:
credentials = [self.normalize_credential(c) for c in credentials]
credentials = [c['geni_value'] for c in filter(isGeniCred, credentials)]
try:
creds = self._cred_verifier.verify_from_strings(self._server.get_pem_cert(),
credentials,
the_slice.urn,
privileges,
options)
except Exception, e:
raise xmlrpclib.Fault('Insufficient privileges', str(e))
This code duplication becomes very annoying when deriving ReferenceAggregateManager. I'm preparing a pull request to reduce this duplication.
=> Reduce code duplication for credentials verification in am3.py 

CHANGES, src/gcf/geni/am/am3.py, src/gcf/geni/am/am_method_context.py, src/gcf/geni/am/api_error_exception.py, src/gcf/geni/am/test_ams.py
This would enable cleaner error messages for clients when the delegate implementation fails.
In the current code, I only see this applied for the `GetVersion` implementation of `am3.AggregateManager`.
Pull request with candidate implementation to follow
=> Generalize catching ApiErrorException when AggregateManager calls the delegate

CHANGES, CONTRIBUTORS.md, README-omni.txt, src/gcf/geni/am/am3.py
Corrected spelling of functions names as explained in issue #846.
=> Fix typos in Provision() for issue #846

CHANGES, CONTRIBUTORS.md, src/gcf/geni/am/am2.py
This is my suggested fix for issue #848.
I've removed all those whitespace errors that appeared in my patch as @tcmitchell asked.
=> keep resources' states updated in am2

CHANGES, src/gcf/omnilib/frameworks/framework_chapi.py
Properly use booleans not char 'f' for expired filters in framework_chapi
=> issue #856: use boolean False not 'f' for `SLICE_EXPIRED` and `PROJECT_EXPIRED`

CHANGES, README-omni.txt, src/gcf/omnilib/chhandler.py, src/gcf/omnilib/frameworks/framework_chapi.py
do not assume project_member_uid is returned by listprojectmembers. But allow and return it if it is returned. This makes omni work with chapi compliant CHs, while also returning the extra info that the GENI CH returns.
=> issue #857: do not assume project_member_uid is returned by listprojectmembers

CHANGES, src/gcf/geni/am/am3.py, src/gcf/geni/am/am_method_context.py
Hello,
I have stumbled into a pain point for my implementation of a BonFIRE delegate. The BonFIRE delegate is stateless, and therefore does not keep track of the relationship between slivers and the related slice.
It relies for that on data accessed through the underlying BonFIRE API, because sliver ids can be mapped to BonFIRE ids. It is possible to request detailed information for a resource, that includes slice id from the BonFIRE API using that BonFIRE id. But getting that information is a privileged call : only the owners/users of the resource can view that information.
Therefore, implementing the `decode_urn` method properly for the BonFIRE delegate would imply being able to access the credentials of the caller to authenticate the user when calling the BonFIRE API. I've been able to …
=> Call am3.decode_urns from AMMethodContext with credential information

CHANGES, src/gcf/omnilib/stitch/objects.py
PG's new error code 28, though I haven't seen it live yet, is clearly another case that stitcher should treat as fatal, and bail if it sees this. Add a block to handle it, after other blocks.
=> issue #861: treat PG error code 28 (generic mapper error) as fatal.

CHANGES, src/gcf/geni/am/aggregate.py, src/gcf/geni/am/am3.py
Fix exception on expire_slivers in GCF AM3. It was storing slivers in the per-slice collection in the aggregate object, but it is supposed to be resources instead. So pass the collection of resources to agg.allocate() and agg.deallocate(), instead of the collection of slivers.
=> Issue #863. AM3 must store resources, not slivers

CHANGES, README-omni.txt, src/gcf/omnilib/chhandler.py
Issue #868: getslicecred ignores the cred in `--slicecredfile`, replacing it if you specify `-o`
Implementing option 4 in my list of proposed solutions to that issue.
=> Issue #868: getslicecred ignores the cred in `--slicecredfile`

CHANGES, src/gcf/omnilib/frameworks/framework_base.py, src/gcf/omnilib/stitch/ManifestRSpecCombiner.py, src/gcf/omnilib/stitch/objects.py
Fix merging EG manifests, to use the VLAN tag on the AM object and edit that into the template (non EG) manifest, rather than relying on the EG manifest (which has different hops and initially is missing the VLAN tags).
=> Tkt873 fix merging EG manifests

CHANGES, INSTALL.macos, INSTALL.txt, README-gcf.txt, README-omni.txt, README-omniconfigure.txt, README.md, README.txt, TROUBLESHOOTING.txt, acceptance_tests/AM_API/README-accept-AMAPI.txt, agg_nick_cache.base, doc/CreatingBinaries.md, doc/IssuingReleases.md, mac_install/INSTALL.txt, omni_config.sample, src/gcf/oscript.py, windows_install/infoAfterFile.rtf, windows_install/package_builder.iss
Addresses issue #814: Change many references to wiki pages on trac.gpolab.bbn.com to github.
Additionally, move the canonical agg_nick_cache to a github page.
=> Issue #814: Change references to trac.gpolab gcf wiki to github

CHANGES, src/gcf/omnilib/stitch/ManifestRSpecCombiner.py
Old code only merged a link that had a VLAN. Now allow it to have a sliver_id to indicate it is the proper manifest, so we can merge EGRE or GRE links. Thanks, Hussam.
=> issue #879: when merging links on a manifest, allow merging non stitched links

CHANGES, README-omni.txt, acceptance_tests/AM_API/README-accept-AMAPI.txt, agg_nick_cache.base, doc/IssuingReleases.md, omni_config.sample, src/gcf/oscript.py
Addresses issues #814 and issue #881.
Make the aggcache come directly from the master branch on github - one less file move.
AND, fix the fetching of the cache to use `urllib2.urlopen` instead of `urllib.urlretrieve` as the latter gets screwed up by the import of `M2Crypto`.
=> Move aggcache to master branch and fix urlretrieve

CHANGES, src/gcf/geni/util/rspec_util.py
The check for an rspec tag is bogus because it does not take XML
namespaces into account. It can cause erroneous errors on valid
rspecs. Remove the check until a proper check can be put in place.
Fixes #885
=> Remove bogus check for 'rspec' tag

CHANGES, src/gcf/sfa/trust/credential.py
Fir the use of `strip()` to extract the `refid` in credentials in the SFA's `credential.py`. Fixes issue #890
=> Fix SFA credential use of strip on refid in issue #890

agg_nick_cache.base
InstaGENI FOAM aggregates are being decommissioned. Remove them from
the aggregate nickname list.
=> Remove InstaGENI FOAM aggregates

src/gcf/omnilib/util/dossl.py
Direct users to renew their certificate at the portal instead of
asking them to email for a new certificate.
=> Remove hardcoded portal help email

CHANGES, agg_nick_cache.base
It appears that "unf-eg" exists in omni "nicknames.txt", but running "getversion" resulted in the following error:
{{{
$ omni -a unf-eg getversion --NoAggNickCache
Downloaded latest `agg_nick_cache` from 'https://raw.githubusercontent.com/GENI-NSF/geni-tools/master/agg_nick_cache.base' and copied to '/home/asydney/.gcf/agg_nick_cache'.
...
Failed to find an AM nickname 'unf-eg'.  If you think this is an error, try using --NoAggNickCache to force the AM nickname cache to update.
}}}
Hence, I've added unf-eg to agg_nick_cache.base.
=> Addresses #902: Added unf-eg to agg_nick_cache.base.

CHANGES, CONTRIBUTORS.md, gcf_config.sample, src/gcf-am.py, src/gcf/geni/am/am3.py
When lots of request are done on the server some connections are closed due to the single thread. 
This option allows multi-thread XMLRPC server
=> Add multi-thread support for AM3

src/gcf/geni/am/am2.py, src/gcf/geni/am/am3.py
The ReferenceAggregateManager was presenting an illegal URN:
"urn:publicid:geni:gpo:gcf+authority+am"
instead of
"urn:publicid:IDN+geni:gpo:gcf+authority+am"
This was due to the lack of the "IDN" parameter on the **publicid_to_urn** method call.
=> ReferenceAggregateManager

README-omni.txt, src/gcf/omnilib/chhandler.py, src/gcf/omnilib/frameworks/framework_base.py, src/gcf/omnilib/frameworks/framework_chapi.py, src/gcf/oscript.py
The clearinghouse fixed a bug with the spelling of EXPIRED. Use the new keywords to be compatible with the latest clearinghouse code.
While there, remove trailing whitespace and update copyrights on the affected files. Don't worry about pycodestyle warnings, there are too many.
Fixes #915
=> Change EXPIRED to SLICE_EXPIRED or PROJECT_EXPIRED

agg_nick_cache.base
The UC Davis ExoGENI rack has been decommissioned.
Fixes #913
=> Remove UC Davis ExoGENI
